version: '3.9'

services:
  zitadel:
    restart: always
    image: ghcr.io/zitadel/zitadel:stable
    command: start-from-init --steps /install.yaml --config /config.yaml --masterkey "YOUR_MASTER_KEY___REPLACE_ME" --tlsMode external
    environment:
      - ZITADEL_DATABASE_COCKROACH_HOST=cockroach
    ports:
      - 8080:8080
    volumes:
      - ./config.yaml:/config.yaml:ro
      - ./install.yaml:/install.yaml:ro
    depends_on:
      cockroach:
        condition: service_healthy
    networks:
      - zitadel

  cockroach:
    restart: always
    image: cockroachdb/cockroach:v22.1.3
    command: start-single-node --insecure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 20s
    ports:
      - 9090:8080
      - 26257:26257
    networks:
      - zitadel

networks:
  zitadel: